#! /bin/ksh
# @ job_name = NV-center
# @ job_type=MPICH
# @ output = job1.$(host).$(jobid).$(stepid).out
# @ error =  job1.$(host).$(jobid).$(stepid).err
# @ class = 72h
# @ restart = no
# @ node = 4
# @ total_tasks = 64
# @ queue
uname -a
. /usr/share/modules/init/bash
echo $SHELL
module add ifort/15.0.3
module add mpi.intel/5.0.3
module list
echo $LOADL_HOSTFILE
cat $LOADL_HOSTFILE
echo $LOADL_TOTAL_TASKS
export I_MPI_DAPL_PROVIDER=ofa-v2-ib0
env | grep I_MPI


mpiexec.hydra -bootstrap ll hostname

VASP="mpiexec.hydra -bootstrap ll gvasp"


$VASP
