#! /usr/bin/env python

import run4v
import argparse

parser = argparse.ArgumentParser(description="A command line interface for run4v")


parser.add_argument("command", help="Input file in OUTCAR format")
parser.add_argument("-v", "--verbose", help="Make the output verbose", action="store_true")
parser.add_argument("-f","--file", help="Print the electron configuration in ascii format", action="store", default="runner.py")


args = parser.parse_args()


if args.verbose:
    print("Making the output verbose...")
    run4v.VERBOSE=True
else:
    run4v.VERBOSE=False


if args.file:
	print args.file

